// Função com a lista de frases de segurança

const frases = [
  "Segurança em primeiro lugar, sorrisos em segundo. Mas não esqueça do EPI!",
  "Use o EPI, a sua mãe agradece!",
  "Trabalhar com segurança é como dançar: um passo errado e você pode se machucar!",
  "O trabalho em equipe é importante, mas manter os dedos longe da máquina é mais ainda!",
  "Se a segurança fosse um jogo, você seria o campeão! Use o EPI e marque pontos!",
  "A pressa é inimiga da perfeição... e da segurança! Vá com calma.",
  "A vida é uma festa, mas a Segurança é o convite! Não esqueça de levar o seu.",
  "Cuidar da sua segurança é o melhor presente que você pode dar para si mesmo (e para sua famiília)!",
  "Segurança no trabalho: o único estilo que nunca sai de moda!",
  "O amor pode até estar no está no ar... mas a segurança também! Use o EPI, proteger seu coração é importante, mas o resto do corpo também.",
  "A segurança é como um abraço: te protege e te faz sentir bem!",
  "Trabalhar com segurança é como um bom café: te dá energia para o dia todo!",
  "Se a segurança fosse uma música, seria a trilha sonora do seu trabalho! Não perca o ritmo!",
  "A prevenção é a chave para um final feliz! Não seja o protagonista de um acidente.",
  "A segurança é a sua melhor amiga no trabalho! Cuide bem dela.",
  "EPIs: a armadura do trabalhador moderno! Vista a sua e conquiste mais um dia!",
  "Trabalhar com segurança é como um quebra-cabeça: cada peça é importante para o sucesso!",
  "A segurança é o ingrediente secreto para um trabalho bem feito! Não esqueça de adicioná-la à receita.",
  "O seu corpo é seu templo, cuide dele com carinho! Use o EPI e trabalhe com segurança.",
  "A segurança é a cereja do bolo do seu trabalho! Não deixe ela cair!",
  "A segurança é investimento, não custo.",
  "Acidentes acontecem quando a prevenção falha.",
  "Antes de começar, pense na segurança. No final, agradeça por ela.",
  "Cinto de segurança: a diferença entre a vida e a tragédia.",
  "Com segurança não se brinca, com a vida muito menos.",
  "Cuide de você, a segurança depende de cada um.",
  "Cuidado nunca é demais, principalmente quando se trata da sua segurança.",
  "Desligue-se do celular, conecte-se com à segurança.",
  "Em caso de dúvida, pergunte! Em caso de risco, pare!",
  "EPIs: sua segunda pele no trabalho.",
  "Equipamento certo, trabalho seguro, vida protegida.",
  "Errar é humano, mas prevenir é inteligente.",
  "Evite atalhos, eles podem levar a acidentes.",
  "Fique atento, a segurança é responsabilidade de todos.",
  "Lembre-se: sua família te espera em casa.",
  "Má postura = Dor futura. Ergonomia é prevenção.",
  "Mantenha o ambiente limpo, a segurança agradece.",
  "Na dúvida, não arrisque. Sua vida vale mais.",
  "Não corra riscos desnecessários, a vida é única.",
  "Não deixe a pressa comprometer a sua segurança.",
  "Não espere o acidente para aprender a lição.",
  "Não importa o trabalho, a segurança vem em primeiro lugar.",
  "Não subestime os riscos, eles podem ser fatais.",
  "O acidente não avisa, a prevenção sim. Olha eu aqui: Previna-se!",
  "O descuido de segundos pode causar danos de anos.",
  "O EPI só protege se você usar.",
  "EPI no armário é igual a carro sem pneu, não te leva a lugar nenhum!",
  "EPI no bolso é como guarda-chuva fechado na chuva, não te protege!",
  "Organização é sinônimo de prevenção.",
  "Pense antes de agir, a segurança é sua aliada.",
  "Prevenir é melhor do que remediar.",
  "Proteja suas mãos, elas são suas ferramentas.",
  "Qualidade de vida começa com segurança no trabalho.",
  "Relaxe, respire fundo e trabalhe com segurança.",
  "Riscos existem, mas a prevenção é a chave.",
  "Seja prudente, a segurança é um presente.",
  "Segurança é um direito, não um favor.",
  "Segurança não é sorte, é atitude.",
  "Segurança no trabalho, tranquilidade em casa.",
  "Seu futuro depende da sua segurança hoje.",
  "Sua saúde é seu maior patrimônio, proteja-a.",
  "Trabalhe com atenção, a segurança ira te acompanhar.",
  "Trabalho seguro, vida feliz.",
  "Valorize a vida, trabalhe com segurança.",
  "Viva com segurança, trabalhe com consciência.",
  "Você é importante, cuide-se!",
  "Zero acidentes, essa é a meta!",
  "Segurança no trampo é tipo crush: não dá pra viver sem!",
  "Trampo seguro é tipo hit do verão: todo mundo curte!",
  "Segurança é o mood do dia!",
  "Segurança no trabalho tem que ser tipo Wi-Fi: sem ela, a gente não funciona!",
];
